/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountRepository: typeof import('./src/components/AccountRepository.vue')['default']
    Bag: typeof import('./src/components/BagView/Bag.vue')['default']
    BagItem: typeof import('./src/components/BagView/BagItem.vue')['default']
    CheckRole: typeof import('./src/components/CheckRole.vue')['default']
    CheckServer: typeof import('./src/components/CheckServer.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GameIcon: typeof import('./src/components/Common/GameIcon.vue')['default']
    GameWorld: typeof import('./src/components/GameWorld.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Icon: typeof import('./src/components/Common/Icon.vue')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    Login: typeof import('./src/components/LoginPanel/Login.vue')['default']
    LoginPanel: typeof import('./src/components/LoginPanel/LoginPanel.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NCountdown: typeof import('naive-ui')['NCountdown']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NModal: typeof import('naive-ui')['NModal']
    NP: typeof import('naive-ui')['NP']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    Register: typeof import('./src/components/LoginPanel/Register.vue')['default']
    RolePowerPanel: typeof import('./src/components/RolePanels/RolePowerPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Common/Setting.vue')['default']
    Theme: typeof import('./src/components/Common/Theme.vue')['default']
  }
}
