export namespace GameText2 {
  export const STR_TYPE_REGISTER_REALNAME = '请输入名字(真实姓名)'
  export const STR_TYPE_REGISTER_IDCARD = '请输入身份证号(18位)'
  export const STR_TYPE_REGISTER_IDCARD_ERROR = '请输入正确的身份证号(18位)'
  export const STR_FRIEND_REMARDS = '好友备注'
  export const STR_FRIEND_REMARDS_INFO
    = '请输入对该玩家的备注，不超过14个字符或7个中文字'
  export const STR_CHANGE_FRIEND_REMARDS = '修改备注'
  export const STR_CHANGE_REMARDS_SUCCESS = '修改备注成功'
  export const STR_REMARDS = '备注'
  export const STR_CHANGE_REMARDS_INFO = '清空备注内容时，表示不对该玩家添加备注。'
  export const STR_YOU_SPEAK_TO = '你对%U说'
  export const STR_BAND_IDCARD = '绑定身份证'
  export const STR_BAND_IDCARD_INFO
    = '强烈建议为您的游戏账号绑定身份证。当您的游戏账号丢失、被盗时，身份证号可作为寻回账号的参考凭证。请务必输入自身正确的身份证号码，身份证一旦与账号绑定，不可解绑。'
  export const STR_BAND_IDCARD_SCUUESS = '绑定成功！您绑定的身份证：%U。'
  export const STR_BAND_IDCARD_ASK
    = '真实名称：/c00FF00%U/p\n身份证号：/c00FF00%U/p\n请仔细确认，一旦绑定身份证号，无法解绑。'
  export const STR_OPENCRAFTMAN_INFO
    = '%U\n\n你可以通过支付/cFF0000%U黄金/p，随机开启一位熔炉大师，提升炼制品质。'
  export const STR_OPENCRAFTMAN_ASK = '继续操作需要支付/cFF0000%U黄金/p,是否确认？'
  export const STR_OPENCRAFTMAN = '随机开启大师'
  export const STR_OPRATOR_FURNACE_ASK
    = '你当前默认使用/cFF0000%U/p进行炼制，是否继续？\n%U'
  export const STR_FURNACE_INCREATENUM_ASK
    = '你的次数已经用完，需要增加次数方可继续炼制，增加/c00FF00%U/p次需要/cFF0000%U/p,是否要增加？'
  export const STR_FURNACE_LEVEL = '%U档'
  export const STR_FURNACE_OPERATE = '开始炼制'
  export const STR_FURNACE_SEE_LEVEL_ITEM_LIST = '档次物品列表'
  export const STR_COUNTRY_CREATE_WAR = '国家强攻指令'
  export const STR_COUNTRY_CREATE_WAR_ID = '请输入对方国家id'
  export const STR_COUNTRY_CREATE_WAR_MONEY1 = '请输入'
  export const STR_COUNTRY_CREATE_WAR_CHIOCE = '请选择宣战方式'
  export const STR_COUNTRY_CREATE_WAR_ASK
    = '需要消耗：/cFFFF00军力值%U/p\n 需要消耗：/cFFFF00国库黄金%U/p\n 需要消耗：/cFFFF00指令书%U/p\n您确定向/cFFFF00【%U】/p国家发动强制攻击吗？'
  export const STR_BACK_LOGIN = '返回登录'
  export const STR_UNION = '盟国'
  export const STR_UNION_SIM = '盟'
  export const STR_UC_LOGIN_SUCCESS = 'UC账号登录成功！'
  export const STR_UC_CHECK_SUCCESS = '验证通过'
  export const STR_UC_LOGIN_ERROR = '错误原因'
  export const STR_OPEN_SKILLSHOP_ALERT_INFO
    = '你可以通过学习技能，提高角色的战斗力！'
  export const STR_REFISTER_INFO
    = '请务必正确填写信息，以便您能顺利注册成为谷得游戏的用户！'
  export const STR_LOGIN_INFO = '请输入您的谷得游戏账号、密码。'
  export const STR_GOOD_LOGIN_NAME = '谷得账号'
  export const STR_TRADE_PLAT = '交易平台'
  export const STR_TYPE_USER_NAME = '请输入谷得游戏账号(4～12位字母或数字)'
  export const STR_MENU_USER_MANAGE = '账号管理'
  export const STR_GAME_HELP = '游戏帮助'
  export const STR_GAME_PLAT_CENTER = '平台中心'
  export const STR_UC_PLAT_CENTER = '九游社区'
  export const STR_INVITE_INFO
    = '如果你收到其他人的邀请，输入邀请码可获得一定的奖励哦。\n(注意：错误的邀请码会导致注册失败,若无邀请码请不要输入或输入0。)'
  export const STR_CHANGE_SEX_INFO = '你确定要改变性别？'
  export const STR_INVITE = '邀请码'
  export const STR_DUIHUAN = '激活码兑换'
  export const STR_FEED_BACK = '用户反馈'
  export const STR_CHECK_NETWORKING_FALSE_INFO = '请检查网络连接'
  export const STR_USE_ITEM_ASK = '你确定要使用%U吗？'
  export const STR_SINA_WEIBA = '微吧入口'
  export const STR_LOGIN_LOTTERYDRAW_COUNT = '抽奖次数：%U'
  export const STR_LOGIN_LOTTERYDRAW_REWARD = '恭喜您，您抽中：'
  export const STR_LOGIN_LOTTERYDRAW_DESC = '抽奖'
  export const STR_LOGIN_LOTTERYDRAW = '登录抽奖'
  export const STR_CHAT_UP = '搭讪'
  export const STR_CHAT_UP2 = '表达好感'
  export const STR_CHAT_NEW = ' (新消息)'
  export const STR_ONLINE_REWARD_TIME = '未到时间领取'
  export const STR_ONLINE_REWARD = '在线奖励'
  export const STR_ONLINE_REWARD_GET = '领奖'
  export const STR_ONLINE_REWARD_SEE_ITEM = '查看物品'
  export const STR_SECOND = '%U秒'
  export const STR_QQ_DIAMOND_OPENSHOP_ALERT = '蓝钻贵族购物八折优惠'
  export const STR_AUTO_SELL_ASK_INFO = '是否出售以下道具：%U\n出售总价：%U铜币'
  export const STR_AUTO_SELL_ALERT_INFO = '成功出售以下道具：%U\n获得：%U铜币'
  export const STR_AUTO_SELL_ALL_PRICES = '总价：%U铜币'
  export const STR_AUTO_SELL_MENU = '智能出售'
  export const STR_AUTO_GET_PET = '确定领取'
  export const STR_AUTO_EVOLVE = '确定进化'
  export const STR_AUTO_MESSAGE = '物品信息'
  export const STR_AUTO_SELL = '确定出售(全部)'
  export const STR_AUTO_KEEP = '保留此物品(不出售)'
  export const STR_ONLINE_REWARD_GET_ITEM_INFO = '你获得：'
  export const STR_AUTO_EVOLVE_SUCCESS = '恭喜您！宠物进化成功!'
  export const STR_CHANGE_ACTIVITY = '充值活动'
  export const STR_CHANGE_ACTIVITY_INFO = '累计充值%U元'
  export const STR_CANNOT_GET = '未可领'
  export const STR_CAN_GET = '可领'
  export const STR_HAS_GET = '已领'
  export const STR_HAS_MONEY = '元'
  export const STR_HAS_SURE = '立即充值'
  export const STR_PET_EVOLVE_ASK = '继续操作需要支付/cFF0000%U铜币/p,是否确认？'
  export const STR_SWITCH_ACCOUNT = '切换账号'
  export const STR_ENCHANT = '附魔'
  export const STR_ENCHANT_VALUE = '附魔值'
  export const STR_ENCHANT_EQUIP = '吸收装备'
  export const STR_ENCHANT_INPUT = '放入吸收'
  export const STR_ENCHANT_KEY_INPUT = '吸收'
  export const STR_ENCHANT_CANCEL = '取下吸收'
  export const STR_ENCHANT_NO_ITEM = '请先将需要吸收的装备放入吸收栏！'
  export const STR_ENCHANT_ASK_INFO
    = '/cFF0000注意装备吸收后无法复原！/p\n即将获得:附魔值 /cc45712%U/p\n吸收装备列表如下:%U'
  export const STR_ENCHANT_ALL = '全部吸收'
  export const STR_ENCHANT_SUCCESS = '吸收成功！ 获得附魔值 /cc45712%U/p'
  export const STR_ENCHANT_SUCCESS_INFO = '装备附魔成功！'
  export const STR_ENCHANT_ATTACH = '附魔属性'
  export const STR_ENCHANT_ENSURE = '确认附魔该装备吗？'
  export const STR_ENCHANT_CHANGE_ASK = '该物品已有%U\n新%U\n是否替换为新附魔属性？'
  export const STR_ENCHANT_NUM_OVER = '吸收装备栏物品不能多于30个！'
  export const STR_ENCHANT_SHOP = '附魔道具商店'
  export const STR_ENCHANT_SHOP_INFO = '/cFFFF00附魔点：%U【合成不会消耗附魔点】/p'
  export const STR_ENCHANT_SELL = '附魔摆摊'
  export const STR_COMMON_SELL = '普通摆摊'
  export const STR_ENCHANT_SELL_EQUIP = '附魔装备'
  export const STR_CHANGE_SELL_ASK = '切换摆摊类型后，当前上架物品将撤下，是否继续？'
  export const STR_CHANGE_SELL_FAIL = '摆摊中无法切换摆摊类型！需先结束当前摆摊。'
  export const STR_ENCHANT_SELL_UP_FAIL = '上架失败！身上附魔值不够。'
  export const STR_ENCHANT_START_FAIL = '摆摊失败！身上附魔值不够。'
  export const STR_ENCHANT_START_SUCCESS
    = '附魔摆摊成功！别人可以通过你的摊位进行附魔操作。'
  export const STR_ENCHANT_SHOP_CHOICE = '选择装备'
  export const STR_ENCHANT_SHOP_USE_ENCNANT = '消耗附魔值: %U'
  export const STR_ENCHANT_SHOP_BUY_INFO
    = '售价：%U\n二次点击确认购买！该操作不会消耗您的附魔值'
  export const STR_ENCHANT_SHOP_BUY_NEED = '消耗 %U。'
  export const STR_ENCHANT_SHOP_ONE_NEED = '每个物品消耗附魔值： %U'
  export const STR_FORMATION = '阵型'
  export const STR_FORMATION_OPTION = '阵型设置'
  export const STR_FORGET_FORMATION = '遗忘'
  export const STR_FORGET_TEAM_NEED = '该阵型需要人数:%U人'
  export const STR_LEARN_FORMATION_SUCCESS = '学习阵型成功！'
  export const STR_FORGET_FORMATION_ASK = '确认是否要遗忘 /cFF0000%U/p ？'
  export const STR_FORGET_FORMATION_SUCCESS = '遗忘阵型成功！'
  export const STR_OPTION_EXECUTED = '已生效'
  export const STR_GM_EMAIL_THEME = '主题'
  export const STR_GM_EMAIL_CONTEXT_NOT_NULL = '问题内容不能为空！'
  export const STR_GM_EMAIL_ASK = '咨询'
  export const STR_GM_EMAIL_APPEAR = '申诉'
  export const STR_GM_EMAIL_RECHARGE_QUESTION = '充值问题'
  export const STR_GM_EMAIL_SUGGEST = '建议反馈'
  export const STR_EQUIP_INDENTIFY_LOW_RESIDUE
    = '剩余普通卷轴/cFFFF00%U个/p\n剩余高级卷轴/cFFFF00%U个/p\n'
  export const STR_VITALITY_NOT_REACH = '未达到'
  export const STR_VITALITY_HAS_REACH = '可领取'
  export const STR_VITALITY_HAS_GET = '已领取'
  export const STR_VITALITY_CAN_NOT_GET = '不可领'
  export const STR_VITALITY_CAN_NOT_GET_INFO
    = '你已领取过同类型的奖励，不能重复领取。'
  export const STR_VITALITY_INFO
    = '1.同一个活跃宝箱每天只能领取一次。\n2.活跃度隔天清零，请及时领取奖品。\n3.%U活跃度额外增加100。'
  export const STR_VITALITY_GET_REWARD = '领取奖励'
  export const STR_VITALITY_GET_REWARD_SUCCESS = '领取奖励成功！'
  export const STR_VITALITY_VIP_ADD_VALUE = '%U+100'
  export const STR_VITALITY_GET_ONLINE_REWARD = '是否打开在线奖励框？'
  export const STR_VITALITY_SUBMIT_DAILY_QUEST = '是否寻路接取日常任务？'
  export const STR_VITALITY_STRONG_EQUIPMENT
    = '您可以在强化界面选择任何一种方式强化装备，包括：鉴定、镶嵌、升星。是否打开强化界面？'
  export const STR_VITALITY_RESOLVE_EQUIPMENT
    = '您可以在道具界面选择物品进行分解。是否打开分解界面？'
  export const STR_VITALITY_ASK_FIND_PATH_SKILL = '是否寻路至技能训练师处？'
  export const STR_VITALITY_DUEL_PLAYER = '是否与其他玩家决斗？'
  export const STR_VITALITY_BUY_GOODS = '是否打开商城界面？'
  export const STR_VITALITY_ENTER_ARENA
    = '进入竞技场并完成一次战斗。是否寻路至竞技场入口处？'
  export const STR_VITALITY_ENTER_MOBPLACE
    = '进入怪物攻城副本并消灭一波怪物。是否寻路至怪物攻城入口处？'
  export const STR_VITALITY_JION_ESCORT = '是否寻路至押镖入口处？'
  export const STR_VITALITY_RECHARGE_MONEY = '是否打开充值界面？'
  export const STR_VITALITY_REFINE_EQUIPMENT
    = '在熔炉商人处进行一次炼制。是否寻路至熔炉商人？'
  export const STR_VITALITY_ANSWER_DAILY_QU = '是否寻路至成就商人？'
  export const STR_VITALITY_JION_DAILY_LUCKY = '是否打开登录抽奖界面？'
  export const STR_VITALITY_JION_CITY_LUCKY = '是否寻路至飞行驿站？'
  export const STR_VITALITY_ASK_NOT_FIND_PATH = '是否打开相应的界面？'
  export const STR_VITALITY_DAILY_LOGIN = '打开在线奖励框。'
  export const STR_VITALITY_DAILY_NOT_HAVE_CITY = '您还未创建自己的城市~'
  export const STR_VITALITY_NOT_OPEN = '活跃度功能未开放！'
  export const STR_VITALITY_ALLVALUE = '活跃度：%U'
  export const STR_VITALITY_LEVEL_NOTENOUGH = '等级未达到分解装备的条件。'
  export const STR_WOOADD_BUTTON = 'WO+中心'
  export const STR_WOOADD_FLOW = '您目前的流量账户余额：'
  export const STR_WOOADD_FLOW_STATE
    = '广东联通携手世界OL回馈广大游戏玩家流量大礼包，每天点击礼包获赠流量奖励后可前往广东联通WO+账户中心查看或领取流量。'
  export const STR_WOOADD_ISMARK_TRUE = '已经签到'
  export const STR_WOOADD_ISMARK_FALSE = '可签到'
  export const STR_WOOADD_REWARD_FLOW = '流量奖励'
  export const STR_MILESTONE_NOT_OPEN_TITLE = ' /cFF0000%U级/p开启第%U章'
  export const STR_MILESTONE_HAS_OPEN_CANGET = '/c00FF00已开启，请领取奖励/p'
  export const STR_MILESTONE_PART_INFO_TIME = '/c00FF00%U内开启将得到额外奖励哦~/p\n'
  export const STR_MILESTONE_PART_INFO = '%U\n相关任务：%U\n任务奖励：%U'
  export const STR_MILESTONE_CHAPTER = '第%U章'
  export const STR_MILESTONE_PART = '第%U节'
  export const STR_MILESTONE_MISSION_NOTOPEN = '未开启'
  export const STR_MILESTONE_MISSION_FINISH = '已完成'
  export const STR_MILESTONE_EXP = '经验'
  export const STR_COUNTRY_ONLINE_INFORM_OPEN = '打开国家管理上线通知'
  export const STR_COUNTRY_ONLINE_INFORM_CLOSE = '关闭国家管理上线通知'
  export const STR_COLORBOX_INFO
    = '%U\n登录天数%U\n登录天数不同获得的奖励也不同，累积/cFFFF00%U天/p更能获得%U哦！'
  export const STR_COLORBOX_DAY_INFO = '第%U天'
  export const STR_COLORBOX_OPEN = '开启宝箱'
  export const STR_COLORBOX_OPEN_ASK1 = '当前天数不符合领奖要求。'
  export const STR_COLORBOX_OPEN_ASK2 = '您确定要开启累计%U天的奖励：%U吗？\n '
  export const STR_COLORBOX_OPEN_ASK3 = '%U累计登录/cFF0000 %U 天/p即可获得“%U”哦！'
  export const STR_PLAYER_TURNMONSTER_INFO = '变身卡属性：\n%U\n技能：%U剩余时间:%U'
  export const STR_PLAYER_TURNMONSTER_CANCEL = '取消变身卡效果'
  export const STR_PLAYER_TURNMONSTER_ASK = '是否确认使用 %U ？'
  export const STR_PLAYER_TURNMONSTER_ASK_TIME = '是否确认使用 %U ,增加变身效果时间？'
  export const STR_PLAYER_TURNMONSTER_ASK_CHA = '是否确认使用 %U ,改变变身效果？'
  export const STR_FIGHT_VALUE = '战力值:'
  export const STR_RANKING = '排名:'
  export const STR_COOLING = '冷却:'
  export const STR_CHALLENGE = '挑战'
  export const STR_SUPER_CHALLENGE = '超前挑战'
  export const STR_RESIDUE_CHALLENGE = '剩余次数:'
  export const STR_RESIDUE_REFRESH_TITLE = '刷新列表'
  export const STR_RESIDUE_REFRESH = '刷新列表需要消耗%U金叶，是否刷新？'
  export const STR_RESIDUE_COOLING_TITLE = '冷却时间'
  export const STR_RESIDUE_COOLING_CLEAR = '清除冷却时间'
  export const STR_RESIDUE_COOLING = '清除冷却时间需要消耗%U金叶，是否确认？'
  export const STR_RESIDUE_COOLING_CHALLENGE = '冷却中,无法进行挑战操作!'
  export const STR_RESIDUE_SURPLUS_TITLE = '增加剩余次数'
  export const STR_RESIDUE_SURPLUS
    = '是否消耗%U黄金增加1次挑战次数？\n(注：每天最多能增加%U次挑战次数)'
  export const STR_RESIDUE_SURPLUS_ADD = '增加挑战次数'
  export const STR_NEW_ARENA_ADD_COUNT_SUCCESS = '增加次数成功!'
  export const STR_NEW_ARENA_REFRESH_SUCCESS = '刷新成功!'
  export const STR_NEW_ARENA_CLEAR_SUCCESS = '清除冷却时间成功!'
  export const STR_NEW_ARENA_ADJUST_SUCCESS = '调整数据成功!'
  export const STR_NEW_ARENA_EXIT_ASK = '是否确定要退出王者争霸竞技场？'
  export const STR_NEW_ARENA_MY_MSG = '我的信息'
  export const STR_NEW_ARENA_ADJUST = '调整'
  export const STR_NEW_ARENA_RANK = '排行榜'
  export const STR_NEW_ARENA_REFRESH = '刷新'
  export const STR_NEW_ARENA_EXIT = '退出竞技场'
  export const STR_NEW_ARENA_ACTIVE_SUCCESS = '报名成功！'
  export const STR_NEW_ARENA_LEAD_CHALLENGE_ASK = '超前挑战需要消耗%U金叶，是否继续？'
  export const STR_NEW_ARENA_RANK_TITLE = '王者争霸竞技场排行榜'
  export const STR_NEW_ARENA_RANK_SELECT = '排名筛选'
  export const STR_NEW_ARENA_MY_RANK = '我的排名'
  export const STR_NEW_ARENA_GET_REWARD = '领取奖励'
  export const STR_NEW_ARENA_REWARD_TITLE = '积分奖励'
  export const STR_NEW_ARENA_REWARD_SCORE = '积分'
  export const STR_NEW_ARENA_RANK_ACTOR_NAME = '名称'
  export const STR_NEW_ARENA_REWARD_POPUP = '恭喜获得：黄金%U,金叶%U,铜币%U'
  export const STR_IDENTIFICATION_CARD = '身份证'
  export const STR_CHINA_PASSPORT = '中国护照'
  export const STR_FOREIGN_PASSPORT = '外国护照'
  export const STR_MTP = '台胞证'
  export const STR_HONGKONG_IDENTIFICATION_CARD = '港澳身份证'
  export const STR_SOLDER_CERTIFICATE = '军官士兵证'
  export const STR_STUDENT_CARD = '学生证'
  export const STR_CARD_SELECT = '选择证件类型'
  export const STR_IDENTIFY_AUTHENTICATION = '身份验证'
  export const STR_IDENTIFY_AUTHENTICATION_CHANGE = '修改身份验证'
  export const STR_IDENTIFY_AUTHENTICATION_NEW = '上传新的身份验证'
  export const STR_IDENTIFY_AUTHENTICATION_CHECK = '查询身份验证'
  export const STR_IDENTIFY_CHANGE_PROCESS
    = '\n注意：修改流程是先填写当前已通过审核的信息并将照片上传，成功后再进行修改。'
  export const STR_INPUT_IDENTIFICATION_CARD_TIP
    = '提示：请输入身份证号码和证件有效期,身份证号码位数为18位.'
  export const STR_INPUT_CHINA_PASSPORT_TIP = '提示：请输入中国护照号码和证件有效期.'
  export const STR_INPUT_FOREIGN_PASSPORT_TIP
    = '提示：请输入外国护照号码和证件有效期.'
  export const STR_INPUT_MTP_TIP = '提示：请输入台胞证号码和证件有效期.'
  export const STR_INPUT_HK_IDENTIFICATION_TIP
    = '提示：请输入港澳身份证号码和证件有效期.'
  export const STR_INPUT_SOLDER_CERTIFICATE_TIP
    = '提示：请输入军官士兵证号码和证件有效期.'
  export const STR_INPUT_STUDENT_CARD_TIP = '提示：请输入学生证号码和证件有效期.'
  export const STR_IDENTIFY_TYPE_VERIFY_PASS = '证件类型:%U\n身份验证审核已通过！'
  export const STR_IDENTIFY_TYPE_VERIFYING = '证件类型:%U\n身份验证审核中，请稍等！'
  export const STR_IDENTIFY_TYPE_CHANGET_VERIFYING
    = '证件类型:%U\n身份验证修改审核中，请稍等！'
  export const STR_IDENTIFY_TYPE_PHOTO_NOT_UPLOAD
    = '证件类型:%U\n身份验证照片没上传！'
  export const STR_IDENTIFY_INPUT_ID = '请输入证件ID'
  export const STR_IDENTIFY_INPUT_ENDDATE = '请输入证件有效期'
  export const STR_IDENTIFY_INPUT_ENDDATE_INFO = '注：证件有效期格式如yyyy-mm-dd'
  export const STR_IDENTIFY_CHANGE_TIP
    = '请重新填写相关信息，并拍张您需要修改的证件照片上传。'
  export const STR_IDENTIFY_SUBMIT_SUCCESS = '身份验证提交成功，等待审核中...'
  export const STR_IDENTIFY_CHANGE_SUBMIT_SUCCESS
    = '请继续上传新的证件资料（如不上传新的证件资料，则保留原验证成功证件信息。）'
  export const STR_MO9_PAY_TITLE = 'MO9快捷支付'
  export const STR_MO9_PAY_ASK = '想充值了吗？何不试试MO9支付，土豪给你垫钱哟！'
  export const STR_CONTINUE_PAY = '继续充值'
  export const STR_PLAYER_COMMON_ATT = '\n普通属性：\n%U'
  export const STR_STR_NEW_ARENA_GET_REWARD = '已获得以下奖励：\n%U'
  export const STR_EQ_UPGRADE_SHOP = '进阶商店'
  export const STR_EQ_UPGRADE = '进阶'
  export const STR_EQ_UPGRADE_EQUIP = '进阶装备'
  export const STR_EQ_UPGRADE_ITEM_COMBIN_ALL = '进阶后装备强化：'
  export const STR_EQ_UPGRADE_ITEM_COMBIN_ALL_INFO
    = '首次进阶必得进阶属性，后续进阶50%几率获得新进阶属性'
  export const STR_EQ_UPGRADE_ITEM_COMBIN_SURE = '确认进阶'
  export const STR_EQ_UPGRADE_ITEM_COMBIN_ERROR = '您没有足够的物品进行进阶！'
  export const STR_COMBIN_EQUIP_ASK = '即将进阶 %U ！\n%U\n是否确认进阶？'
  export const STR_EQ_UPGRADE_GET_INFO = '进阶获得：'
  export const STR_EQ_UPGRADE_ITEM = '您当前鉴定的装备：'
  export const STR_EQ_UPGRADE_GET_ATTRIBUTE = '进阶属性：'
  export const STR_EQ_UPGRADE_GET_ITEM_INFO
    = '请选择进阶材料，进阶后不可恢复！\n%U（再次点击确认选择）'
  export const STR_EQ_IDENTIFY_COMMON = '传统鉴定'
  export const STR_EQ_IDENTIFY_UPGRADE = '进阶鉴定'
  export const STR_EQ_IDENTIFY_CANNOT_UPGRADE
    = '对不起，您的装备没有进阶，无法使用进阶鉴定。'
  export const STR_EQ_INDENTIFY_UPGRADE_RESIDUE = '剩余进阶鉴定卷轴/cFFFF00%U个/p\n'
  export const STR_EQ_INDENTIFY_UPGRADE_ITEM_POWER = '进阶效果%U:%U'
  export const STR_EQ_INDENTIFY_UPGRADE_INFO
    = '\n/cff0000进阶装备保留宝石、升星和附魔属性。/p'
  export const STR_BAG_HAVE_NULL_CAN_UPGRADE = '背包中没有可鉴定的进阶装备!'
  export const STR_BAG_HAVE_NULL_CAN_UPGRADESTAR = '背包中没有可进阶升星的进阶装备!'
  export const STR_ITEM_UPGRADE_STAR = '进阶升星'
  export const STR_ITEM_STAR = '升星'
  export const STR_ITEM_UPGRADE_STAR_SUCCEE = '装备/c00ff00进阶升星成功/p！\n'
  export const STR_ITEM_UPGRADE_STAR_FAIL = '装备/cff0000进阶升星失败/p！\n'
  export const STR_ITEM_UPGRADESTAR_NUM = '进阶升星：%U --> %U \n'
  export const STR_ITEM_STAR_POWERVALUE4 = '进阶效果1: %U -> %U \n'
  export const STR_ITEM_STAR_POWERVALUE5 = '进阶效果2: %U -> %U \n'
  export const STR_ITEM_STAR_POWERVALUE6 = '进阶效果3: %U -> %U \n'
  export const STR_ITEM_STAR_POWERVALUE7 = '进阶效果4: %U -> %U \n'
  export const STR_ITEM_UPGRADESTAR_COUNT = '剩余进阶升星卷轴: /cFFFF00%U/p 个 \n'
  export const STR_SEAL = '封印'
  export const STR_PET_SEAL_INFO = '%U\n封印有几率获得与宠物品质相对应的技能书:\n%U'
  export const STR_PET_SEAL_ASK
    = '是否封印%U？\n需要消耗%U\n成功率%U%\n/cff0000(注：封印宠物不论成功或失败，宠物都会消失不可恢复)/p'
  export const STR_PET_SEAL_FAIL = '封印失败!'
  export const STR_PET_SEAL_SUCCESS = '封印成功!'
  export const STR_PET_SEAL_RS_INFO = '封印获得%U'
  export const STR_QUESTION = '问题'
  export const STR_ANSWER = '答案'
  export const STR_QQ_SAFE_LOCK_ANSWER_QUESTION = '设置安全问题'
  export const STR_QQ_SAFE_LOCK_RESET_QUESTION = '重置安全问题'
  export const STR_QQ_SAFE_LOCK_FIND = '找回安全锁'
  export const STR_QQ_SAFE_LOCK_QUESTION_SET = '安全锁问题设置'
  export const STR_QQ_SAFE_LOCK_QUESTION_ANSWER = '安全锁问题回答'
  export const STR_QQ_SAFE_LOCK_QUESTION_INFO
    = '安全锁一旦设置不能取消，只能通过安全问题重置；如果忘记安全问题答案，请联系致电客服申请重置。'
  export const STR_QUESTION_ANSWER = '问题回答'
  export const STR_QQ_SAFE_LOCK_ANSWER_NULL = '答案不能为空！'
  export const STR_QQ_SAFE_LOCK_ANSWER_INFO
    = '请记住您设置的安全锁问题，往后找回或更改安全锁需要输入问题及答案进行验证\n'
  export const STR_BATTLEGROUND_ENEMY_DEFEND_ARMY = '敌方防守部队'
  export const STR_BATTLEGROUND_DEFEND_ARMY = '我方防守部队'
  export const STR_BATTLEGROUND_ATTACK_ARMY = '我方进攻部队'
  export const STR_BATTLEGROUND_ENEMY_ATTACK_ARMY = '敌方进攻部队'
  export const STR_BATTLEGROUND_APPLY_ATTACK_ARMY = '加入攻击部队'
  export const STR_BATTLEGROUND_APPLY_DEFEND_ARMY = '加入防守部队'
  export const STR_BATTLEGROUND_TOWER_INFO
    = '	       塔楼被己方势力占领后，防守方只能在中间2分钟无敌时间进行驻扎和换人，成功防守10分钟可获得50势力积分。攻打塔楼的队伍数量无限制，可排队轮流攻打防守的队伍，但必须把全部防守队伍打败才能攻占塔楼。\n'
  export const STR_BATTLEGROUND_DEFEND_CANNOMOVE = '塔楼攻防中不能行走！'
  export const STR_BATTLEGROUND_INFO
    = '	                     	战场开始时间：%U \n	                     	战场结束时间：%U \n'
  export const STR_BATTLEGROUND_INFO_ESCAPE_TIME
    = '	                 	逃跑惩罚剩余时间：%U \n'
  export const STR_BATTLEGROUND_INFO_MAP_CD_TIME
    = '	             	进入战场地图冷却剩余时间：%U \n'
  export const STR_BATTLEGROUND_INFO_MAP_READY
    = '战场开始前5分钟，已报名的玩家可以提前进入准备地图。\n'
  export const STR_BATTLEGROUND_APPLY = '战场报名'
  export const STR_BATTLEGROUND_ENTER = '进入战场准备地图'
  export const STR_BATTLEGROUND_ENTER_MAP = '战场总地图'
  export const STR_BATTLEGROUND_QUITE_FIGHT = '退出塔楼攻防战'
  export const STR_BATTLEGROUND_STATUS_FIGHT = '塔楼当前处于 /cFF0000争夺/p 状态 \n'
  export const STR_BATTLEGROUND_STATUS_INVINCIBLE
    = '塔楼当前处于 /c00FF00无敌/p 状态 \n'
  export const STR_BATTLEGROUND_CITYGATE = '城门当前的耐久度为： %U / %U \n'
  export const STR_BATTLEGROUND_SIEGE
    = '，成功地对敌人城门造成了严重的破坏，请继续努力，把城门摧毁。'
  export const STR_BATTLEGROUND_DEFENDERS
    = '，成功地维修了己方的城门，请继续努力，把城门维修得坚不可摧。'
  export const STR_BATTLEGROUND_ROB_ATTACK
    = '这名玩家正在进行/c00FF00 攻城 /p任务，你确定要攻击他吗？该劫镖任务无需提交押金，如果你成功击败他，将阻止他破坏你所属势力的城门，同时获得战场功勋。如果失败了，你将会返回准备地图。'
  export const STR_BATTLEGROUND_ROB_DEFENDERS
    = '这名玩家正在进行/c00FF00 守城 /p任务，你确定要攻击他吗？该劫镖任务无需提交押金，如果你成功击败他，将阻止他维修他所属势力的城门，同时获得战场功勋。如果失败了，你将会返回准备地图。'
  export const STR_BATTLEGROUND_FORCES_BELONGS = '	       所属势力：'
  export const STR_BATTLEGROUND_FORCES_SNOWFIELDS = '雪原'
  export const STR_BATTLEGROUND_FORCES_VOLCANO = '烈焰峰'
  export const STR_BATTLEGROUND_FORCES_SWAMP = '沼泽'
  export const STR_BATTLEGROUND_GLORY_INTEGRAL = '战场功勋'
  export const STR_BATTLEGROUND_GLORY_INTEGRAL_SHOP = '战场功勋商店'
  export const STR_INTEGRAL_BATTLE_INFO = '战场功勋%U'
  export const STR_BATTLEGROUND_LIST_NOTHING = '暂无队伍可以查看'
  export const STR_BATTLE = '战场'
  export const STR_BATTLE_SIM = '战'
  export const STR_BATTLE_BATTLEGROUND_OUT = '战场战斗时间到'
  export const STR_BATTLE_BATTLEGROUND_RANK0 = '新兵'
  export const STR_BATTLE_BATTLEGROUND_RANK1 = '三等兵'
  export const STR_BATTLE_BATTLEGROUND_RANK2 = '二等兵'
  export const STR_BATTLE_BATTLEGROUND_RANK3 = '一等兵'
  export const STR_BATTLE_BATTLEGROUND_RANK4 = '上等兵'
  export const STR_BATTLE_BATTLEGROUND_RANK5 = '下士'
  export const STR_BATTLE_BATTLEGROUND_RANK6 = '中士'
  export const STR_BATTLE_BATTLEGROUND_RANK7 = '上士'
  export const STR_BATTLE_BATTLEGROUND_RANK8 = '军士长'
  export const STR_BATTLE_BATTLEGROUND_RANK9 = '少尉'
  export const STR_BATTLE_BATTLEGROUND_RANK10 = '中尉'
  export const STR_BATTLE_BATTLEGROUND_RANK11 = '上尉'
  export const STR_BATTLE_BATTLEGROUND_RANK12 = '少校'
  export const STR_BATTLE_BATTLEGROUND_RANK13 = '中校'
  export const STR_BATTLE_BATTLEGROUND_RANK14 = '上校'
  export const STR_BATTLE_BATTLEGROUND_RANK15 = '少将'
  export const STR_BATTLE_BATTLEGROUND_RANK16 = '将军'
  export const STR_BATTLE_BATTLEGROUND_RANK17 = '大将军'
  export const STR_BATTLE_BATTLEGROUND_RANK18 = '元帅'
  export const STR_BATTLE_BATTLEGROUND_RANK19 = '大元帅'
  export const STR_MOBILE_TRAFFIC_CARD_PHOTO_TITLE = '请输入手机号码:'
  export const STR_GUESSGAME_EXIT_ASK = '是否确定完成%U？'
  export const STR_GUESSGAME_LEVEL_INFO = '本局:%U'
  export const STR_NEXT = '下一关'
  export const STR_SURE = '决定'
  export const STR_FINISHED = '完成'
  export const STR_GUESSGAME_ENTRY_NEED_INFO
    = '游戏名称:%U \n 等级需求:%U \n 可玩次数:%U\n 奖励:/c00FF00%U/p\n需要/cFFFF00%U/p，是否继续？'
  export const STR_GUESSGAME_NEXT_INFO = '总关数:%U 胜利条件：过%U关'
  export const STR_GUESSGAME_CAN_NOT_NEXT = '你还没选择足够的图标!'
  export const STR_COST_REWARD_WIN_INFO = '通关：%U'
  export const STR_COST_REWARD_GET = '恭喜获得：\n%U'
  export const STR_COST_REWARD_GET_INFO
    = '编号%U的奖励在活动期间不能同时领取，只可领取其中一个，确定领取奖励？'
  export const STR_COST_REWARD_INFO
    = '活动时间：%U 到 %U \n 活动期间您在指定商店累计消费总金额：\n%U'
  export const STR_COST_REWARD_NEED = '需求'
  export const STR_NO_SUPPER = '该版本不支持该功能！'
  export const CONSUMER_ACCUMULATED = '消费累积'
  export const EGAMEFREE_MORE_GAME = '更多游戏'
  export const QQ_LOGIN = 'qq登陆'
  export const WX_LOGIN = '微信登陆'
  export const CAPTAIN = '队长'
  export const MEMBER = '队员'
  export const MEMBER_LV = '%U级'
  export const STR_FIGHT = '出战'
  export const STR_REST = '休息'
  export const STR_SERVER = '跨服'
  export const STR_SERVER_SIM = '跨'
}
